name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest
        uses: Akshay090/github-action-neural-style-transfer@master
        with:
          path: "tests/sample_image.jpg"
      - uses: actions/upload-artifact@v1
        with:
          name: styled_image
          path: styled_output